  const T_iVector List_m0pShift[] = /* compare "mindist2.c" */
    {
      {     0,     0,     0 },
      { -STBF,     0,     0 },
      {  STBF,     0,     0 },
      {     0, -STBF,     0 },
      {     0,  STBF,     0 },
      {     0,     0, -STBF },
      {     0,     0,  STBF },
      { -STBF, -STBF,     0 },
      {  STBF,  STBF,     0 },
      { -STBF,     0, -STBF },
      {  STBF,     0,  STBF },
      {     0, -STBF, -STBF },
      {     0,  STBF,  STBF },
      { -STBF,  STBF,     0 },
      {  STBF, -STBF,     0 },
      { -STBF,     0,  STBF },
      {  STBF,     0, -STBF },
      {     0, -STBF,  STBF },
      {     0,  STBF, -STBF },
      { -STBF, -STBF, -STBF },
      {  STBF,  STBF,  STBF },
      { -STBF, -STBF,  STBF },
      {  STBF,  STBF, -STBF },
      { -STBF,  STBF, -STBF },
      {  STBF, -STBF,  STBF },
      { -STBF,  STBF,  STBF },
      {  STBF, -STBF, -STBF }
    };
