#!/usr/bin/env sh

THRESHOLD="0.01"

if [ "$1" = "help" ]; then
	echo "Usage: dlsall [THRESHOLD]"
	echo ""
	echo "Run DLS-76 on all frameworks in 'strudat'"
	echo "Those with an R-value below THRESHOLD (default $THRESHOLD) are converted to CIF format"
	echo "Requires KRIBER and DLS-76"
	exit 1
fi

if [ "$1" != "" ]; then
	THRESHOLD=$1
fi

for FW in `grep '^\*' strudat | cut -c2-`; do
	echo $FW | kriber reacs $@ addo wriid exit > /dev/null
	dls76 dlsinp
	RVAL=`grep "0R=SQRT" dls76.out | tail -n1 | grep "[0-9]\.[0-9]*" -o --color=never`
	if (( $(echo "$RVAL < $THRESHOLD" | bc -l) )); then
		echo $FW - $RVAL "-->" $FW"_dls.cif"

		echo $FW | kriber reacs $@ addo wricif wriid exit > /dev/null

		grep -v "^[OT]" structure.cif > structure_dls.cif

		python << END >> structure_dls.cif

###  PYTHON
fin = open('nfilea.inp','r')
for line in fin:
    if line.startswith('NATOM'):
        print line[7:13], line[13:21], line[21:29], line[29:37]
fin.close()
### /PYTHON
END

	mv structure_dls.cif $FW"_dls.cif"

	else
		echo $FW - $RVAL
	fi

done

unlink nfilea.inp
unlink dlsinp
unlink dls76.out