#!/usr/bin/env sh

if [ x"$1" = x"" ]; then
	echo "Error: Invalid argument, please supply a focus output file."
	echo "Usage: focus2strudat \$(focus log file)"
	exit 0
fi

if [ $1 = "help" ]; then
	echo "Usage: focus2strudat \$(focus log file)"
fi

fo2hist $1
fo2hist $1 | cut -c2- > tf
section $1 Framework -take=tf > strudat
unlink tf