#!/usr/bin/env sh

if [ "$1" = "" ]; then
	echo "Error: Invalid argument, please supply focus output file(s)."	
	echo "Usage: focus_check [filenames]"
	exit 0
fi

if [ "$1" = "help" ]; then
	echo "Usage: focus_check FILE [FILE ...]"
	echo ""
	echo "Parses and summarizes out put from FOCUS output files."
	echo "Generates histogram of solutions."
	exit 1
fi

rm -rf all.out

tot_time=0.0
tot_nwot=0
tot_nsol=0

for file in "$@"
do
		fn=${file%.*}
	   	echo ""
	   	echo ""
    	echo "${file}"
        echo "Random seed: `grep "RandomInitialization" ${file} -m1 | grep -o '[0-9]\+'`"
        
		sed "s/*Fw/*Fw_${fn}_/g" ${file} >> all.out
        
        nwot=`grep -c "WoT" ${file}`
        nsol=`grep -c "*Fw" ${file}`

		var=`grep 'Exit$' ${file} | grep -o "[0-9]\+\.[0-9]\+"`
		
		if [ -n "$var" ]; then
			arr=($var)
			tval=${arr[0]}
			hrs=`bc <<< "scale=2;$tval/3600"`
			
			if [ $nsol -ne 0 ]; then
				rate=`bc <<< "scale=2;$tval/$nsol"`
			else
				rate='-'
			fi

			echo "Time taken: $hrs hr; $rate sec/sol"
	
			tot_time=`bc <<< "scale=2;$tot_time + $tval"`
		fi
		
		tot_nwot=`expr $tot_nwot + $nwot`
		tot_nsol=`expr $tot_nsol + $nsol`

        printf "Trials:   %6d\n" $nwot
        printf "Solutions:%6d\n" $nsol

		fo2hist ${file}



done

if [ $# -gt 1 ]; then
	echo ""
	echo "----------------------------"
	
	file="all.out"
	echo "${file}"
	# cat 1?.out > ${file}
	
	hrs=`bc <<< "scale=2;$tot_time/3600"`
	
	if [ $tot_nsol -ne 0 ]; then
		rate=`bc <<< "scale=2;$tot_time/$tot_nsol"`
		echo "Time taken: $hrs hr; $rate sec/sol"
	else
		rate='-'
	fi
	
	printf "Trials:   %6d\n" $tot_nwot
	printf "Solutions:%6d\n" $tot_nsol

	fo2hist ${file}
	echo ""
	echo "grep '*Fw' ${file} -m NUMBER -n | tail -n 1"
	echo "Where number is the number of the Fw + 1"
fi