#!/usr/bin/env sh

if [ "$1" = "help" ]; then
	echo "Usage: strudat2cif (kriber_command ...)"
	echo ""
	echo "Convert all frameworks in a strudat file to cif format"
	echo "For example: \"strudat2cif addo\" to add oxygens to the framework and write cif file after"
	exit 1
fi

for FW in `grep '^\*' strudat | cut -c2-`; do
	echo $FW | kriber reacs $@ wricif exit
	mv structure.cif $FW.cif
done
